version: "3.7"
services:
  postgres:
    container_name: "postgres-store"
    image: "postgres:14.2"
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
      POSTGRES_DB: store
    volumes:
      - postgres:/data/postgres
  pgadmin:
    container_name: "pgadmin-store"
    image: "dpage/pgadmin4"
    hostname: pgadmin
    depends_on:
      - postgres
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin:
